### ISSUE TITLE
python2 specific?

### ISSUE THREAD

**Issue by mathog** [lastz/lastz#30]
Is it just me or do the python parts of this package, or at least some of them, only work with python2?  For instance, when installed on CentOS 8 this happens:

```
python2 $TOPDIR/bin/qcode_to_scores.py -help
unknown argument: -help

qcode_to_scores [options] > lastz_score_file
  --scaleto=<max>         scale scores to give desired max
  --symmetric             map probabilities symmetrically
  --hoxd70                use HOXD70 (lastz default scores) for probabilities
  --code.target=<codefile> specify the quantum code for rows (LASTZ target)
  --code.query=<codefile>  specify the quantum code for columns (LASTZ query)
  --code=<codefile>       specify the quantum code for both rows *and* columns
  --creator=<string>      set name of creator to write as a comment in output
  --nocreator             inhibit creator comment in output
  <base>.target:<prob>    set target background probability of a nucleotide
  <base>.query:<prob>     set query background probability of a nucleotide
  <base>:<prob>           set background probability of a nucleotide for *both*
                          target and query 
  <basepair>:<prob>       set basepair substitution probability;  first base is
                          for target, second for query

python3 $TOPDIR/bin/qcode_to_scores.py -help
  File "/usr/common/modules/el8/x86_64/software/lastz/1.04.03-CentOS-vanilla/bin/qcode_to_scores.py", line 127
    for (s,p) in hoxd70:
                       ^
TabError: inconsistent use of tabs and spaces in indentation
```
Also the shebang

`#!/usr/bin/env python
`
fails on CentOS 8, which has only python2 and python3.  I have a tool to "reshebang" python scripts, but it defaults to python3 when the version is ambiguous, and here at least some scripts would not run.

**Comment by rsharris** [comment]
Yes, anything in python is for python2. Much of it written before the first python 3 release.

I doubt it would take much to convert it to 3. I don't think there's anything at all sophisticated going on in the python stuff, just glue for operations quicker to implement in python.

**Comment by rsharris** [comment]
FWIW. I've (just now) corrected the indentation problem that python 3 flagged.

**Comment by mathog** [comment]
> FWIW. I've (just now) corrected the indentation problem that python 3 flagged.

On just that one or on all the scripts with similar problems?

Since python2 has EOL'd it may be worth taking 15 minutes or so to clean up the python scripts to work with python3, and then change the shebang's to 

`#!/usr/bin/env python3
`
so the problem will not come up again when python 4 comes out (who knows when that might be) and we find it has its own backwards compatibility issues with python 3.

Thanks.

**Comment by rsharris** [comment]
I only fixed the one. Sorry. I will look for others.

Simplest solution in the short term is to run things in a python2 virtual environment. I'll look at doing the python3 conversion "soon" but not sure how soon that will be.

Not clear to me how to distribute this without causing backward compatibility issues for people still using python2. End-of-life or not, if someone has an existing pipeline I don't want to do something to cause them grief. The self-tests in the Makefile also make use of some of those tools.

I suppose the easiest thing is to rename the current tools directory as "tools.python2", and include a note in the installation section telling people that if your are still using python 2 rename that directory.

Thanks for reporting this.

**Comment by rsharris** [comment]
(for my own knowledge)
The shebangs-in-python concept is discussed in python PEP 0394, here:
https://www.python.org/dev/peps/pep-0394/#recommendation

**Comment by rsharris** [comment]
I've made syntax changes which (a) satisfy python3 and (b) python2 doesn't complain about. Ran the self tests with python2 as the default python (the self tests make use of many of the python scripts). As best I can tell I have not broken python2 support yet.

I have not addressed the shebang issue yet. That is likely to be the last thing I change, as I'm still not certain from my interpretation of PEP 0394 of what the correct shebang should be.

At least one self test fails when python3 is the default python. This was caused by lav_compare.py's use of file() to open a file. I will need to dig a little to discover what the python3 equivalent is.

**Comment by rsharris** [comment]
I've added a tools.python3 directory. Eventually this will replace the current tools directory.

@mathog , could you test whether these are functional in your python3 environment? You would need to discard the current tools directory and rename tools.python3 to tools.

I've only lightly tested these. I ran the lastz self tests in a python3 conda environment (this may not use *all* the tools though). And I ran each tool with "--help". More complete testing will have to wait.

At this point the only differences between the two directories involves prints to stderr, and the shebangs.

**Comment by mathog** [comment]
cloned at 10:20AM 07/23 PST and compiled.

As a first pass I just ran them all with "./script.py --help".  Some would not run that way.  That does not mean that they have a Python 3 issue, they may just not handle "--help" as the sole argument.  For whatever reason, these two failed:

```
hsx_file.py
./hsx_file.py: line 80: syntax error near unexpected token `('
merge_masking_intervals.py
Traceback (most recent call last):
  File "./merge_masking_intervals.py", line 81, in <module>
    if __name__ == "__main__": main()
  File "./merge_masking_intervals.py", line 39, in main
    assert (len(argv) == 1), "give me no arguments"
AssertionError: give me no arguments
```

I am not sure if install_py.py works or not, there was no output.

The others all seemed to run OK.

Then the base_tests were run:

```
mv tools tools.python2
ln -s tools.python3 tools
make base_test
#all were SUCCESS

```

So better.

**Comment by rsharris** [comment]
Thanks very much for checking those. I do appreciate that.

I've pushed fixes for hsx_file and merge_masking_intervals.

hsx_file isn't intended to be run from the command line. It now tells the user that rather than trying to run in whatever default shell the user has.

merge_masking_intervals doesn't support any command line arguments. Rather than raise an exception it now reports that to stderr as it exits. Of course, it would be better if it had a usage report that told you what it did. It doesn't appear that I've documented that anywhere in the readme either. I will need to dig through old project notes to see why I created that. 

I should probably remove install_py from the repo. I was surprised that it was in there. This assumes the user has a particular file hierarchy that matches some hierarchy I had long ago (and might have been a 'standard' user file system layout for our lab at that time, circa 2004). I'm reticent to remove it though, without having a better idea about why I put it in there in the first place. I will look into that.

**Comment by rsharris** [comment]
I'm going to try writing the chainer in python. Not sure how much time I will have to devote to it. Hopefully will have it working by next weekend.

**Comment by rsharris** [comment]
I've added an external chaining program, tools/chain_alignments.py. Currently only implemented in python2.

Obviously I have not tested this much. I ran a small contrived example that kept ≈20 segments out of ≈100.

"lastz --nogapped | chain_alignments" matched "lastz --chain --nogapped" on the first attempt. I was completely surprised -- I was expecting I'd have to do some debugging to get things close to working.

In more detail, the outputs of these two were identical:
 `lastz apple.fa orange.fa --nogapped--format=general-:name1,start1,end1,name2,start2,end2,strand2,score
  | tee nogapped.unchained.dat
  | chain_alignments} --format=name1,start1,end1,name2,start2,end2,strand2,score
  > nogapped.externally_chained.dat
`

`lastz apple.fa orange.fa --nogapped --chain --format=general-:name1,start1,end1,name2,start2,end2,strand2,score
  > nogapped.chained.dat
`

The implementation is a (mostly) direct translation of the C code to python. There are a couple differences which I expect might produce slightly different results in some cases. Scoring in the python version uses floating point, where the lastz version uses 32-bit signed integer scoring (for the non-float build of lastz, which is the usual one). Integer scoring could potentially overflow, thus lastz clips scores (of chains) to the maximum int. This is not necessary it the python version. The python version needs you to tell it the score of an A-to-A match; this is the only way it knows how your scores relate to base-by-base alignment events.

Input to the python version is, essentially, the same format as a segment file, except that (a) the python version requires a score for each segment, and (b) the python version will allow you to have other columns and to have the columns in any order you like. See the usage report form the python for more details. Output is the same format as the input.
